// Generated by `pulse gen` — do not edit by hand.
import type { Id, CollabField } from "@onveloz/pulse-schema";

declare module "@onveloz/pulse-schema" {
  interface PulseDataModel {
    users: {
      _id: Id<"users">;
      _creationTime: number;
      name: string;
      email: string;
      role: "admin" | "member";
    };
    messages: {
      _id: Id<"messages">;
      _creationTime: number;
      authorId: Id<"users">;
      channelId: Id<"channels">;
      body: string;
      editedAt?: number;
    };
    channels: {
      _id: Id<"channels">;
      _creationTime: number;
      name: string;
      isPrivate: boolean;
    };
    counters: {
      _id: Id<"counters">;
      _creationTime: number;
      name: string;
      value: number;
    };
    accounts: {
      _id: Id<"accounts">;
      _creationTime: number;
      name: string;
      balance: number;
    };
    transfers: {
      _id: Id<"transfers">;
      _creationTime: number;
      fromId: Id<"accounts">;
      toId: Id<"accounts">;
      amount: number;
    };
    notes: {
      _id: Id<"notes">;
      _creationTime: number;
      title: string;
      body: CollabField;
    };
  }
}
