import type {
  AnyTableDefinition,
  SchemaDefinition,
  ValidatorDescription,
} from "@pulse/schema";

/** Render a validator description as a TypeScript type expression. */
export function tsType(desc: ValidatorDescription): string {
  switch (desc.kind) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "any":
      return "unknown";
    case "literal":
      return JSON.stringify(desc.value);
    case "id":
      return `Id<${JSON.stringify(desc.table)}>`;
    case "doc":
      return `Doc<${JSON.stringify(desc.table)}>`;
    case "collab":
      return "CollabField";
    case "array":
      return `${tsType(desc.element)}[]`;
    case "union":
      return desc.members.map(tsType).join(" | ");
    case "optional":
      // Field-level optionality is handled by the caller; the type is the inner.
      return tsType(desc.inner);
    case "object": {
      const fields = Object.entries(desc.fields).map(([k, v]) => {
        const opt = desc.optional.includes(k) ? "?" : "";
        const inner = v.kind === "optional" ? v.inner : v;
        return `${k}${opt}: ${tsType(inner)}`;
      });
      return `{ ${fields.join("; ")} }`;
    }
  }
}

/**
 * Generate the `_generated/dataModel.ts` module: a `declare module` augmentation
 * of `PulseDataModel` with one literal `Doc` per table (system fields + user
 * fields). Emitting literal members (rather than deriving from `typeof schema`)
 * deliberately avoids the `v → doc → Doc → PulseDataModel → typeof schema → v`
 * type cycle — a generated dataModel of Doc/Id types per table.
 */
export function generateDataModel(
  schema: SchemaDefinition<Record<string, AnyTableDefinition>>,
): string {
  const described = schema.describe();
  const tableBlocks = Object.entries(described).map(([table, { fields }]) => {
    const lines = [
      `      _id: Id<${JSON.stringify(table)}>;`,
      `      _creationTime: number;`,
    ];
    for (const [field, desc] of Object.entries(fields)) {
      const isOptional = desc.kind === "optional";
      const inner = isOptional ? desc.inner : desc;
      lines.push(`      ${field}${isOptional ? "?" : ""}: ${tsType(inner)};`);
    }
    return `    ${table}: {\n${lines.join("\n")}\n    };`;
  });

  // Only import the type names actually referenced, to satisfy strict TS.
  const json = JSON.stringify(described);
  const imports = ["Id"];
  if (json.includes('"kind":"collab"')) imports.push("CollabField");

  return `// Generated by \`pulse gen\` — do not edit by hand.
import type { ${imports.join(", ")} } from "@pulse/schema";

declare module "@pulse/schema" {
  interface PulseDataModel {
${tableBlocks.join("\n")}
  }
}
`;
}
