// File-based migrations (Prisma/Drizzle style): each migration is an editable SQL
// file plus a *snapshot* of the schema's "live shape" recorded after it. The next
// migration is generated by diffing the current schema against the last snapshot —
// so generation never touches a database. The same `diffSchema` engine used for
// live diffing does the work; the snapshot just stands in for the live DB.

import type { AnyTableDefinition, SchemaDefinition } from "@onveloz/pulse-schema";
import { fieldToColumn, pgType } from "./ddl.js";
import {
  diffSchema,
  dropStatement,
  type LiveColumn,
  type LiveSchema,
  type SchemaDiff,
} from "./diff.js";

type AnySchema = SchemaDefinition<Record<string, AnyTableDefinition>>;

/** A schema snapshot in the same shape the diff engine compares against:
 *  table → column → {type, notNull}, plus index names. Recorded (as JSON) after
 *  each migration so the next `generate` can diff offline, no database needed. */
export interface Snapshot {
  version: 1;
  columns: LiveSchema;
  indexes: string[];
  /** Index name → its ordered columns, so a same-name column change is noticed.
   *  Optional for back-compat: snapshots written before this field are read with
   *  unknown columns, which the diff treats as a match (no spurious re-create). */
  indexColumns?: Record<string, string[]>;
}

export const EMPTY_SNAPSHOT: Snapshot = { version: 1, columns: {}, indexes: [], indexColumns: {} };

/** Convert a schema definition into the snapshot (live shape) that applying it
 *  would produce: the engine-managed system columns plus each field's lowered
 *  column, and the declared index names (`<table>_<index>`). */
export function schemaToSnapshot(schema: AnySchema): Snapshot {
  const described = schema.describe();
  const columns: LiveSchema = {};
  const indexes: string[] = [];
  const indexColumns: Record<string, string[]> = {};
  for (const [table, { fields, indexes: idxs }] of Object.entries(described)) {
    const cols: Record<string, LiveColumn> = {
      _id: { type: "uuid", notNull: true },
      _creation_time: { type: "bigint", notNull: true },
    };
    for (const [field, desc] of Object.entries(fields)) {
      const inner = desc.kind === "optional" ? desc.inner : desc;
      const nullable = desc.kind === "optional" || desc.kind === "collab";
      cols[fieldToColumn(field)] = { type: pgType(inner), notNull: !nullable };
    }
    columns[table] = cols;
    for (const ix of idxs ?? []) {
      const name = `${table}_${ix.name}`;
      indexes.push(name);
      indexColumns[name] = ix.columns.map(fieldToColumn);
    }
  }
  return { version: 1, columns, indexes, indexColumns };
}

/** Diff the current schema against the previous snapshot (or empty, for the first
 *  migration). Reuses the live-diff engine with the snapshot standing in for the DB. */
export function diffAgainstSnapshot(schema: AnySchema, prev: Snapshot | null): SchemaDiff {
  const base = prev ?? EMPTY_SNAPSHOT;
  const cols = base.indexColumns ?? {};
  const liveIndexes = new Map(base.indexes.map((name) => [name, cols[name] ?? []]));
  return diffSchema(base.columns, schema, liveIndexes);
}

/** Render an editable migration SQL file from a diff. Additive and alter
 *  statements are live; destructive drops are commented out — the developer
 *  uncomments only the ones they intend (no accidental data loss). */
export function renderMigration(tag: string, diff: SchemaDiff): string {
  const out: string[] = [
    `-- ${tag}`,
    `-- Generated by \`pulse migrate\`. Edit freely; destructive drops are commented out by default.`,
    ``,
  ];
  for (const s of diff.additive) out.push(s);
  if (diff.alters.length) {
    out.push(
      ``,
      `-- Type / nullability changes — review (can fail or lose data on a non-empty table):`,
    );
    for (const s of diff.alters) out.push(s);
  }
  if (diff.destructive.length) {
    out.push(``, `-- Destructive — DATA LOSS. Uncomment the ones you intend to apply:`);
    for (const d of diff.destructive) out.push(`-- ${dropStatement(d)}`);
  }
  return out.join("\n") + "\n";
}

/** The on-disk journal: migrations in order, by sequential index. */
export interface JournalEntry {
  idx: number;
  tag: string;
}
export interface Journal {
  version: 1;
  entries: JournalEntry[];
}

export const EMPTY_JOURNAL: Journal = { version: 1, entries: [] };

/** A migration's `<NNNN>_<slug>` tag, e.g. `(3, "add score!")` → `0003_add_score`. */
export function migrationTag(idx: number, name: string): string {
  const slug =
    (name || "migration")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "") || "migration";
  return `${String(idx).padStart(4, "0")}_${slug}`;
}

/** Deterministic short hash of a migration's SQL (FNV-1a, no deps), so an edit to
 *  an already-applied file can be detected as drift at `deploy` time. */
export function hashSql(sql: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < sql.length; i++) {
    h ^= sql.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(16).padStart(8, "0");
}
