// Generated by `pulse gen` — do not edit by hand.
import type { Id } from "@onveloz/pulse-schema";

declare module "@onveloz/pulse-schema" {
  interface PulseDataModel {
    cursors: {
      _id: Id<"cursors">;
      _creationTime: number;
      clientId: string;
      x: number;
      y: number;
      country: string;
      color: string;
      updatedAt: number;
      channel: string;
      scrollY: number;
      selStart: number;
      selEnd: number;
    };
  }
}
